#!/bin/bash

if [[ $# -ne 7 ]]; then
  echo "usage: ./lrl <sorted.bam> <target_genes.bed> <enriched_regions.bed> <reference.fasta> <repeats.bed> <annotation.gff> <output_prefix>"
  exit
fi

bam=$1
bed=$2
enriched_region=$3
ref=$4
repeats=$5
gff=$6
out_prefix=$7

if [ ! -s $bam ]; then
  echo "ERROR: BAM file '$bam' does not exist or is empty"
  exit
fi

if [ ! -s $ref ]; then
  echo "ERROR: Reference FASTA file '$ref' does not exist or is empty"
  exit
fi

if [ ! -s $bed ]; then
  echo "ERROR: Target BED file '$bed' does not exist or is empty"
  exit
fi

if [ ! -s $enriched_region ]; then
  echo "ERROR: Enriched regions BED file '$enriched_region' does not exist or is empty"
  exit
fi

if [ ! -s $repeats ]; then
  echo "ERROR: Repeat BED file '$repeats' does not exist or is empty"
  exit
fi

if [ ! -s $gff ]; then
  echo "ERROR: Annotatin GFF file '$gff' does not exist or is empty"
  exit
fi

mkdir -p ${out_prefix}


# fusions
# usage: Call gene fusions/translocations from whole-genome nanopore seq BAM file [-h] [--outdir OUTDIR] [--full] [--genes GENES [GENES ...]] bed repeats bams [bams ...]
if [ ! -s ${out_prefix}/fusions.json ]; then
  python fusions.py --outdir $out_prefix --full $bed $repeats $bam --one_sided leukemia_promiscuous_genes.txt > $out_prefix/fusions.json
fi

# MAF
if [ ! -s ${out_prefix}/karyotype.maf ]; then
  ./maf_rust/target/release/nano_maf ${bam} ${enriched_region} ${repeats} ./maf_rust/T2T_1Kgenomes_min10.tsv 20 > ${out_prefix}/karyotype.maf
fi


# karyotyping
# usage: Digital karyotyping from BAM or binned depth file [-h] [--repeats REPEATS] [--outdir OUTDIR] [--read_lim READ_LIM] [-v] input [input ...]
if [ ! -s ${out_prefix}/karyotype.json ]; then
  if [ -s ${out_prefix}/coverage_1Mbp_bins.tsv ]; then
    python lrdk_with_maf.py ${out_prefix}/coverage_1Mbp_bins.tsv --repeats $repeats --outdir ${out_prefix} --maf ${out_prefix}/karyotype.maf --adaptive ${enriched_region} --json > ${out_prefix}/karyotype.json
  else
    python lrdk_with_maf.py ${bam} --repeats $repeats --outdir ${out_prefix} --maf ${out_prefix}/karyotype.maf --adaptive ${enriched_region} --json > ${out_prefix}/karyotype.json
  fi
fi

# FLT3, UBTF
# usage: Predict ITD and allelic ratio from targeted nanopore sequencing [-h] bam out
if [ ! -s ${out_prefix}/itd.json ]; then
  python itd.py ${bam} > ${out_prefix}/itd.json
fi

# CNVs
if [ ! -s ${out_prefix}/cnvs.json ]; then
  python call_CNVs.py $bam $bed ${out_prefix}/coverage_1Mbp_bins.tsv ${out_prefix}/fusions.json > ${out_prefix}/cnv.json
fi

# SNVs
# usage: Identify coding variation in nanopore adaptive sampling BAM file [-h] [--genes GENES [GENES ...]] [--phase] bam ref gff
if [ ! -s ${out_prefix}/genotypes.json ]; then
  python targeted_SNVs.py $bam $ref $gff --phase > ${out_prefix}/genotypes.json
fi

python make_report.py ${out_prefix} ${out_prefix}.report.docx 0.2.0
